import { FileText, Download, ExternalLink, FileSpreadsheet, BarChart3, Wrench } from 'lucide-react'
import './Downloads.css'

interface DownloadItem {
  name: string
  description: string
  filename: string
  date: string
  icon?: 'report' | 'guide' | 'analysis' | 'engineering'
}

const SUPABASE_URL = 'https://ezlmmegowggujpcnzoda.supabase.co'

// Downloads catalog - Pete adds new files here
const downloads: DownloadItem[] = [
  {
    name: 'Powder Press Requirements Specification',
    description: 'Engineering requirements for compression bonded neo magnet press - 1M parts/month capacity, tight tolerances, vendor qualifications',
    filename: 'press-requirements-spec.pdf',
    date: '2026-01-27',
    icon: 'engineering'
  },
  {
    name: 'BMC Combined Magnet Analysis',
    description: 'Full tonnage analysis combining mag.neo.csv and neo2.csv - 78.4 tons over 3 years with methodology and conclusions',
    filename: 'bmc-magnet-analysis-combined.pdf',
    date: '2026-01-27',
    icon: 'analysis'
  },
  {
    name: 'BMC Magnet Usage Analysis (File 1)',
    description: 'Weight by grade analysis for mag.neo.csv with calculation methodology',
    filename: 'magnet-analysis.pdf',
    date: '2026-01-27',
    icon: 'analysis'
  },
  {
    name: 'North American Co-Packer White Paper 2026',
    description: 'Comprehensive market analysis with industry trends, competitive landscape, and co-packer directory',
    filename: 'copacker-whitepaper-2026.pdf',
    date: '2026-01-27',
    icon: 'report'
  },
  {
    name: 'Clawdbot Educational Guide',
    description: 'Complete guide covering memory system, security, setup, and best practices',
    filename: 'clawdbot-guide.pdf',
    date: '2026-01-27',
    icon: 'guide'
  }
]

export default function Downloads() {
  const getUrl = (filename: string) => 
    `${SUPABASE_URL}/storage/v1/object/public/downloads/${filename}`

  const getIcon = (icon?: string) => {
    switch (icon) {
      case 'analysis':
        return <BarChart3 size={32} />
      case 'report':
        return <FileSpreadsheet size={32} />
      case 'engineering':
        return <Wrench size={32} />
      default:
        return <FileText size={32} />
    }
  }

  return (
    <div className="downloads-page">
      <header className="downloads-header">
        <h1>Downloads</h1>
        <p>Documents and files generated by Pete</p>
      </header>

      <div className="downloads-list">
        {downloads.map((item, i) => (
          <div key={i} className="download-card">
            <div className="download-icon">
              {getIcon(item.icon)}
            </div>
            <div className="download-info">
              <h3>{item.name}</h3>
              <p>{item.description}</p>
              <span className="download-date">Added: {item.date}</span>
            </div>
            <div className="download-actions">
              <a 
                href={getUrl(item.filename)} 
                download={item.filename}
                className="download-btn"
              >
                <Download size={18} />
                <span>Download</span>
              </a>
              <a 
                href={getUrl(item.filename)} 
                target="_blank" 
                rel="noopener noreferrer"
                className="view-btn"
              >
                <ExternalLink size={18} />
              </a>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
