import { useState, useEffect } from 'react'
import { FileText, Download, ExternalLink, FileSpreadsheet, BarChart3, Loader2, Wrench } from 'lucide-react'
import { supabase } from '../lib/supabase'
import './Downloads.css'

interface DownloadItem {
  name: string
  description: string
  filename: string
  date: string
  icon?: 'report' | 'guide' | 'analysis' | 'engineering'
  url?: string
}

// Static catalog of known downloads with metadata
const downloadsCatalog: Record<string, Omit<DownloadItem, 'filename' | 'url'>> = {
  'bmc-magnet-analysis-combined.pdf': {
    name: 'BMC Combined Magnet Analysis',
    description: 'Full tonnage analysis combining mag.neo.csv and neo2.csv with methodology and conclusions',
    date: '2026-01-27',
    icon: 'analysis'
  },
  'magnet-analysis.pdf': {
    name: 'BMC Magnet Usage Analysis (File 1)',
    description: 'Weight by grade analysis for mag.neo.csv with calculation methodology',
    date: '2026-01-27',
    icon: 'analysis'
  },
  'copacker-whitepaper-2026.pdf': {
    name: 'North American Co-Packer White Paper 2026',
    description: 'Comprehensive market analysis with industry trends, competitive landscape, and co-packer directory',
    date: '2026-01-27',
    icon: 'report'
  },
  'clawdbot-guide.pdf': {
    name: 'Clawdbot Educational Guide',
    description: 'Complete guide covering memory system, security, setup, and best practices',
    date: '2026-01-27',
    icon: 'guide'
  },
  'press-requirements-spec.pdf': {
    name: 'Powder Press Requirements Specification',
    description: 'Engineering requirements for compression bonded neo magnet press - 1M parts/month capacity, tight tolerances',
    date: '2026-01-27',
    icon: 'engineering'
  }
}

export default function Downloads() {
  const [downloads, setDownloads] = useState<DownloadItem[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const SUPABASE_URL = 'https://ezlmmegowggujpcnzoda.supabase.co'

  useEffect(() => {
    loadDownloads()
  }, [])

  const loadDownloads = async () => {
    try {
      setLoading(true)
      
      // List files from Supabase storage 'downloads' bucket
      const { data: files, error: listError } = await supabase.storage
        .from('downloads')
        .list('', { limit: 100 })

      if (listError) throw listError

      // Map files to download items with metadata
      const items: DownloadItem[] = (files || [])
        .filter(file => file.name.endsWith('.pdf'))
        .map(file => {
          const catalog = downloadsCatalog[file.name]
          const url = `${SUPABASE_URL}/storage/v1/object/public/downloads/${file.name}`
          
          return {
            filename: file.name,
            url,
            name: catalog?.name || formatFilename(file.name),
            description: catalog?.description || 'Document generated by Pete',
            date: catalog?.date || new Date(file.created_at).toISOString().split('T')[0],
            icon: catalog?.icon || 'report'
          }
        })
        .sort((a, b) => b.date.localeCompare(a.date)) // Most recent first

      setDownloads(items)
    } catch (err) {
      console.error('Failed to load downloads:', err)
      setError('Failed to load downloads')
    } finally {
      setLoading(false)
    }
  }

  const formatFilename = (filename: string) => {
    return filename
      .replace('.pdf', '')
      .replace(/-/g, ' ')
      .replace(/\b\w/g, c => c.toUpperCase())
  }

  const getIcon = (icon?: string) => {
    switch (icon) {
      case 'analysis':
        return <BarChart3 size={32} />
      case 'report':
        return <FileSpreadsheet size={32} />
      case 'engineering':
        return <Wrench size={32} />
      default:
        return <FileText size={32} />
    }
  }

  if (loading) {
    return (
      <div className="downloads-page">
        <header className="downloads-header">
          <h1>Downloads</h1>
          <p>Documents and files generated by Pete</p>
        </header>
        <div className="downloads-loading">
          <Loader2 size={32} className="spinner" />
          <span>Loading downloads...</span>
        </div>
      </div>
    )
  }

  return (
    <div className="downloads-page">
      <header className="downloads-header">
        <h1>Downloads</h1>
        <p>Documents and files generated by Pete</p>
      </header>

      {error && <p className="downloads-error">{error}</p>}

      {downloads.length === 0 ? (
        <div className="downloads-empty">
          <FileText size={48} />
          <p>No downloads available yet</p>
        </div>
      ) : (
        <div className="downloads-list">
          {downloads.map((item, i) => (
            <div key={i} className="download-card">
              <div className="download-icon">
                {getIcon(item.icon)}
              </div>
              <div className="download-info">
                <h3>{item.name}</h3>
                <p>{item.description}</p>
                <span className="download-date">Added: {item.date}</span>
              </div>
              <div className="download-actions">
                <a 
                  href={item.url} 
                  download={item.filename}
                  className="download-btn"
                >
                  <Download size={18} />
                  <span>Download</span>
                </a>
                <a 
                  href={item.url} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="view-btn"
                >
                  <ExternalLink size={18} />
                </a>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
